### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jjanderson** [Limych/HomeAssistantComponents#1]
Hi,

Great component, use this to get a better thermostat result in room with multiple temp sensors..

Just one point... in your example, you have a typo.. you have spelt entities incorrectly....

sensor:
  - platform: average_temperature
    entites: -->> Should be entities <<--
      - weather.gismeteo
      - sensor.owm_temperature
      - sensor.dark_sky_temperature

**Comment by Limych** [comment]
Thank you
